"""Add last_login field to User model

Revision ID: 958df3747058
Revises: 6d37f2b342d0
Create Date: 2025-04-24 20:37:20.984069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958df3747058'
down_revision = '6d37f2b342d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
