"""Redo migration with new Client fields

Revision ID: a6ec8a380125
Revises: fa22f8834c5a
Create Date: 2025-04-25 02:14:04.305190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6ec8a380125'
down_revision = 'fa22f8834c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('registered_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_client_registered_by', 'users', ['registered_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client_registered_by', type_='foreignkey')
        batch_op.drop_column('registered_by')
        batch_op.drop_column('registered_at')

    # ### end Alembic commands ###
