"""Add registered_at and registered_by to Client

Revision ID: fa22f8834c5a
Revises: 318122984805
Create Date: 2025-04-25 01:35:07.204842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa22f8834c5a'
down_revision = '318122984805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('registered_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_client_registered_by', 'users', ['registered_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client_registered_by', type_='foreignkey')
        batch_op.drop_column('registered_by')
        batch_op.drop_column('registered_at')

    # ### end Alembic commands ###
