"""Remove last_login field to User model

Revision ID: ff5574abe59b
Revises: 958df3747058
Create Date: 2025-04-24 20:42:23.537898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5574abe59b'
down_revision = '958df3747058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
